// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suyervjawrmbyyxetblv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1eWVydmphd3JtYnl5eGV0Ymx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzQwNzQsImV4cCI6MjA3MDg1MDA3NH0.1IoZXMrAfDaue6uFtNWT7ocVMwYbbrQ2xOu-HlyquxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});